server:
  port: 8081

spring:
  application:
    name: Order

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/orderflow
    username: postgres
    password: postgres

  sql:
    init:
      mode: never

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: orderflow-audit-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN

orderflow:
  kafka:
    bootstrap-servers: localhost:9092
    auto-offset-reset: earliest

    topic-settings:
      partitions: 1
      replicas: 1

    consumer-groups:
      audit: orderflow-audit-service
      inventory: orderflow-inventory-service
      order: orderflow-order-service
      shipment: orderflow-shipment-service
      payment: orderflow-payment-service

    topics:
      order-created: order.created
      order-confirmed: order.confirmed
      order-cancelled: order.cancelled
      inventory-reserved: inventory.reserved
      inventory-failed: inventory.failed
      inventory-released: inventory.released
      shipment-created: shipment.created
      shipment-shipped: shipment.shipped
      shipment-delivered: shipment.delivered
      payment-created: payment.created
      payment-completed: payment.completed
      payment-failed: payment.failed
      payment-expired: payment.expired

  payment:
    simulation:
      enabled: true
      success-rate: 100
      provider: MOCK_PAYMENT_PROVIDER

  scheduler:
    unpaid-payments:
      enabled: true
      expiration-days: 3
      fixed-delay-ms: 3600000
