server:
  port: 8081

spring:
  application:
    name: Order

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/orderflow
    username: postgres
    password: postgres

  sql:
    init:
      mode: never

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: orderflow-audit-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN

orderflow:
  kafka:
    bootstrap-servers: localhost:9092
    consumer-group-id: orderflow-audit-service
    auto-offset-reset: earliest

    topics:
      order-created: order.created
      order-confirmed: order.confirmed
      order-cancelled: order.cancelled